/*****************************************************************************
 *
 * Copyright (c) 2000 - 2019, Lawrence Livermore National Security, LLC
 * Produced at the Lawrence Livermore National Laboratory
 * LLNL-CODE-442911
 * All rights reserved.
 *
 * This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
 * full copyright notice is contained in the file COPYRIGHT located at the root
 * of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
 *
 * Redistribution  and  use  in  source  and  binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of  source code must  retain the above  copyright notice,
 *    this list of conditions and the disclaimer below.
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
 *    documentation and/or other materials provided with the distribution.
 *  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
 *    be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
 * ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
 * LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
 * DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
 * CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
 * LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
 * OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 *****************************************************************************/

// ************************************************************************* //
//                            avtGMSHFileFormat.C                           //
// ************************************************************************* //

#include <avtGMSHFileFormat.h>

#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cctype>
#include <locale>
#include <iterator>

#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>
#include <vtkCellType.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>
#include <DebugStream.h>

#include <InvalidDBTypeException.h>
#include <InvalidVariableException.h>

// trim from start (in place)
static inline void ltrim(std::string &s) {
  s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](int ch) {
        return !std::isspace(ch);
      }));
}

// trim from end (in place)
static inline void rtrim(std::string &s) {
  s.erase(std::find_if(s.rbegin(), s.rend(), [](int ch) {
        return !std::isspace(ch);
      }).base(), s.end());
}

// trim from both ends (in place)
static inline void trim(std::string &s) {
  ltrim(s);
  rtrim(s);
}

std::vector<std::string> split(std::string s)
{
  std::istringstream iss(s);
  std::vector<std::string> tokens(std::istream_iterator<std::string>{iss},
                                  std::istream_iterator<std::string>());

  return tokens;
}

// ****************************************************************************
//  Method: avtGMSHFileFormat constructor
//
//  Programmer: benjamin -- generated by xml2avt
//  Creation:   Sat Oct 5 15:54:07 PST 2019
//
// ****************************************************************************

avtGMSHFileFormat::avtGMSHFileFormat(const char *filename)
: avtSTSDFileFormat(filename)
{
  m_filename = filename;
  std::ifstream ins(filename);
  if (!ins) {
    EXCEPTION1(InvalidDBTypeException, "Can't open file.");
  }

  std::string line;
  std::getline(ins, line);
  trim(line);
  if (line != "$MeshFormat") {
    EXCEPTION1(InvalidDBTypeException, "File must start with $MeshFormat.");
  }

  std::getline(ins, line);
  trim(line);
  std::vector<std::string> version_line = split(line);
  std::string version = version_line[0];
  int file_type = std::stoi(version_line[1]);

  if ((version.rfind("2.", 0) == 0) and (file_type == 0)) {
    debug4 << "GMSH ASCII file version " << version << "\n";
  } else {
    EXCEPTION1(InvalidDBTypeException, "File version unsupported by this reader.");
  }

  ins.close();
}

// ****************************************************************************
//  Method: avtGMSHFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: benjamin -- generated by xml2avt
//  Creation:   Sat Oct 5 15:54:07 PST 2019
//
// ****************************************************************************

void
avtGMSHFileFormat::FreeUpResources(void)
{
}

// ****************************************************************************
//  Method: avtGMSHFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: benjamin -- generated by xml2avt
//  Creation:   Sat Oct 5 15:54:07 PST 2019
//
// ****************************************************************************

void
avtGMSHFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
  //
  // CODE TO ADD A MESH
  //
  std::string meshname = "airfoil";
  //
  // AVT_RECTILINEAR_MESH, AVT_CURVILINEAR_MESH, AVT_UNSTRUCTURED_MESH,
  // AVT_POINT_MESH, AVT_SURFACE_MESH, AVT_UNKNOWN_MESH
  avtMeshType mt = AVT_UNSTRUCTURED_MESH;
  //
  int nblocks = 1;//  <-- this must be 1 for STSD
  int block_origin = 0;
  int spatial_dimension = 3;
  int topological_dimension = 3;
  double *extents = NULL;
  //
  // Here's the call that tells the meta-data object that we have a mesh:
  //
  AddMeshToMetaData(md, meshname, mt, extents, nblocks, block_origin,
                    spatial_dimension, topological_dimension);
  //

  //
  // CODE TO ADD A SCALAR VARIABLE
  //
  // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
  std::string varname = "var";
  //
  // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
  avtCentering cent = AVT_NODECENT;
  //
  //
  // Here's the call that tells the meta-data object that we have a var:
  //
  AddScalarVarToMetaData(md, varname, meshname, cent);
  //
}


// ****************************************************************************
//  Method: avtGMSHFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: benjamin -- generated by xml2avt
//  Creation:   Sat Oct 5 15:54:07 PST 2019
//
// ****************************************************************************

vtkDataSet *
avtGMSHFileFormat::GetMesh(const char *meshname)
{
  std::ifstream ins(m_filename);
  if (!ins) {
    EXCEPTION1(InvalidDBTypeException, "Can't open file.");
  }

  std::string line;
  while (std::getline(ins, line)) {
    trim(line);
    m_data.push_back(line);
  }

  ins.close();

  // TODO:
  // Lire les coordonnées des noeuds (entre les balises $Nodes et $EndNodes).
  std::vector<std::string>::iterator nodes_start_it = std::find(m_data.begin(), m_data.end(), "$Nodes");
  int nodes_index = std::distance(m_data.begin(), nodes_start_it);
  int nnodes = std::stoi(m_data[nodes_index + 1]);
  int nodes_start_index = nodes_index + 2;
  std::vector<std::string>::iterator nodes_end_it = std::find(m_data.begin(), m_data.end(), "$EndNodes");
  int nodes_end_index = std::distance(m_data.begin(), nodes_end_it);

  std::vector<double> x, y, z;
  for (int i = nodes_start_index; i < nodes_end_index; ++i) {
    std::vector<std::string> toks_vertices = split(m_data[i]);
    x.push_back(std::stod(toks_vertices[1]));
    y.push_back(std::stod(toks_vertices[2]));
    z.push_back(std::stod(toks_vertices[3]));
  }

  // TODO:
  // Puis utiliser la structure de données VTK appropriée pour les stocker.
  int npts = x.size();
  vtkPoints *points = vtkPoints::New();
  points->SetNumberOfPoints(npts);
  for (int i = 0; i < npts; i++){
    points->SetPoint (i, x[i], y[i], z[i]);
  }


  // TODO:
  // Initialiser un maillage non structuré à partir de cette dernière structure.
  vtkUnstructuredGrid *grid = vtkUnstructuredGrid::New();
  grid->SetPoints(points);
  points->Delete();


  // TODO:
  // Lire les éléments (triangles et tetrahèdres) entre les balises $Elements et $EndElements.
  std::vector<std::string>::iterator elements_start_it =
    std::find(m_data.begin(), m_data.end(), "$Elements");
  int elements_index = std::distance(m_data.begin(), elements_start_it);
  int elements_data_start_index = elements_index + 2;
  std::vector<std::string>::iterator elements_end_it = std::find(m_data.begin(), m_data.end(), "$EndElements");
  int elements_end_index = std::distance(m_data.begin(), elements_end_it);

  // elements_data : element_id, cell_ids, ...
  std::vector<std::vector<int>> elements_data;

  for (int i = elements_data_start_index; i < elements_end_index; ++i) {
    std::vector<std::string> toks_elms = split(m_data[i]);
    // Ajout des triangles et tetrahedres.
    std::vector<int> elm;
    int nb = toks_elms.size();

    if (toks_elms[1] == "2") {
      elm.push_back(2);
      elm.push_back(std::stoi(toks_elms[nb-3])-1);
      elm.push_back(std::stoi(toks_elms[nb-2])-1);
      elm.push_back(std::stoi(toks_elms[nb-1])-1);
      elements_data.push_back(elm);
    } else if (toks_elms[1] == "4") {
      elm.push_back(4);
      elm.push_back(std::stoi(toks_elms[nb-4])-1);
      elm.push_back(std::stoi(toks_elms[nb-3])-1);
      elm.push_back(std::stoi(toks_elms[nb-2])-1);
      elm.push_back(std::stoi(toks_elms[nb-1])-1);
      elements_data.push_back(elm);
    }
  }

  // TODO:
  // Allouer l'espace mémoire utilisé par le maillage en fonction du nombre de cellules.
  grid->Allocate(elements_data.size());



  int nb_tri = 0;
  int nb_tet = 0;
  // TODO:
  // Utiliser la structure de données VTK appropriée pour stocker les éléments du maillage.
  vtkIdList *ids = vtkIdList::New();
  for (auto& elm : elements_data) {
    if (elm[0] == 2) {
      nb_tri++;
      ids->SetNumberOfIds(3);
      ids->SetId(0, elm[1]);
      ids->SetId(1, elm[2]);
      ids->SetId(2, elm[3]);
      grid->InsertNextCell(VTK_TRIANGLE, ids);
    }
    if (elm[0] == 4) {
      nb_tri++;
      ids->SetNumberOfIds(4);
      ids->SetId(0, elm[1]);
      ids->SetId(1, elm[2]);
      ids->SetId(2, elm[3]);
      ids->SetId(3, elm[4]);
      grid->InsertNextCell(VTK_TETRA, ids);
    }
  }


  return grid;
}

// ****************************************************************************
//  Method: avtGMSHFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: benjamin -- generated by xml2avt
//  Creation:   Sat Oct 5 15:54:07 PST 2019
//
// ****************************************************************************

vtkDataArray *
avtGMSHFileFormat::GetVar(const char *varname)
{
  vtkFloatArray *var = vtkFloatArray::New();


  std::vector<std::string>::iterator elements_start_it =
    std::find(m_data.begin(), m_data.end(), "$Elements");
  int elements_index = std::distance(m_data.begin(), elements_start_it);
  int elements_data_start_index = elements_index + 2;
  std::vector<std::string>::iterator elements_end_it = std::find(m_data.begin(), m_data.end(), "$EndElements");
  int elements_end_index = std::distance(m_data.begin(), elements_end_it);

  // elements_data : element_id, cell_ids, ...
  std::vector<std::vector<int>> elements_data;

  for (int i = elements_data_start_index; i < elements_end_index; ++i) {
    std::vector<std::string> toks_elms = split(m_data[i]);
    // Ajout des triangles et tetrahedres.
    std::vector<int> elm;
    int nb = toks_elms.size();

    if (toks_elms[1] == "2" && toks_elms[2] == "2") {
      elm.push_back(2);
      elm.push_back(std::stoi(toks_elms[nb-4])-1);
      elm.push_back(std::stoi(toks_elms[nb-5])-1);
      elements_data.push_back(elm);
    } else if (toks_elms[1] == "4" && toks_elms[2] == "2") {
      elm.push_back(4);
      elm.push_back(std::stoi(toks_elms[nb-5])-1);
      elm.push_back(std::stoi(toks_elms[nb-6])-1);
      elements_data.push_back(elm);
    }
  }

  // TODO:
  // Allouer l'espace mémoire utilisé par le maillage en fonction du nombre de cellules.
  var->Allocate(elements_data.size());

  int ntuples = elements_data.size(); // this is the number of entries in the variable.
  // vtkFloatArray *rv = vtkFloatArray::New();
  var->SetNumberOfTuples(ntuples);
  for (int i = 0 ; i < ntuples ; i++)
  {
       var->SetTuple1(i, elements_data[i][1]);  // you must determine value for ith entry.
  }

  return var;








  // int nb_tri = 0;
  // int nb_tet = 0;
  // // TODO:
  // // Utiliser la structure de données VTK appropriée pour stocker les éléments du maillage.
  // vtkIdList *ids = vtkIdList::New();
  // for (auto& elm : elements_data) {
  //   if (elm[0] == 2) {
  //     nb_tri++;
  //     ids->SetNumberOfIds(3);
  //     ids->SetId(0, elm[1]);
  //     ids->SetId(1, elm[2]);
  //     ids->SetId(2, elm[3]);
  //     grid->InsertNextCell(VTK_TRIANGLE, ids);
  //   }
  //   if (elm[0] == 4) {
  //     nb_tri++;
  //     ids->SetNumberOfIds(4);
  //     ids->SetId(0, elm[1]);
  //     ids->SetId(1, elm[2]);
  //     ids->SetId(2, elm[3]);
  //     ids->SetId(3, elm[4]);
  //     grid->InsertNextCell(VTK_TETRA, ids);
  //   }
  // }
  //
  //
  // return grid;
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  //
  // return nullptr;

  //
  // If you have a file format where variables don't apply (for example a
  // strictly polygonal format like the STL (Stereo Lithography) format,
  // then uncomment the code below.
  //
  // EXCEPTION1(InvalidVariableException, varname);
  //

  //
  // If you do have a scalar variable, here is some code that may be helpful.
  //
  // int ntuples = XXX; // this is the number of entries in the variable.
  // vtkFloatArray *rv = vtkFloatArray::New();
  // rv->SetNumberOfTuples(ntuples);
  // for (int i = 0 ; i < ntuples ; i++)
  // {
  //      rv->SetTuple1(i, VAL);  // you must determine value for ith entry.
  // }
  //
  // return rv;
  //
}


// ****************************************************************************
//  Method: avtGMSHFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: benjamin -- generated by xml2avt
//  Creation:   Sat Oct 5 15:54:07 PST 2019
//
// ****************************************************************************

vtkDataArray *
avtGMSHFileFormat::GetVectorVar(const char *varname)
{
  return nullptr;

  //
  // If you have a file format where variables don't apply (for example a
  // strictly polygonal format like the STL (Stereo Lithography) format,
  // then uncomment the code below.
  //
  // EXCEPTION1(InvalidVariableException, varname);
  //

  //
  // If you do have a vector variable, here is some code that may be helpful.
  //
  // int ncomps = YYY;  // This is the rank of the vector - typically 2 or 3.
  // int ntuples = XXX; // this is the number of entries in the variable.
  // vtkFloatArray *rv = vtkFloatArray::New();
  // int ucomps = (ncomps == 2 ? 3 : ncomps);
  // rv->SetNumberOfComponents(ucomps);
  // rv->SetNumberOfTuples(ntuples);
  // float *one_entry = new float[ucomps];
  // for (int i = 0 ; i < ntuples ; i++)
  // {
  //      int j;
  //      for (j = 0 ; j < ncomps ; j++)
  //           one_entry[j] = ...
  //      for (j = ncomps ; j < ucomps ; j++)
  //           one_entry[j] = 0.;
  //      rv->SetTuple(i, one_entry);
  // }
  //
  // delete [] one_entry;
  // return rv;
  //
}
